name: viphyslim
channels:
  - defaults
dependencies:
  - python=3.13.5
  - pip
  - pip:
      - biopython==1.85
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.59.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.5
      - memory-profiler==0.61.0
      - mpi4py==4.1.0
      - numpy==2.3.2
      - packaging==25.0
      - pillow==11.3.0
      - psutil==7.0.0
      - pyaml==25.7.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - PyYAML==6.0.2
      - six==1.17.0